// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqYq4-zDBKlcP5GUUaV2m9Sqaj_ssA05s',
    appId: '1:541861431225:web:8eb05749cde81c4c479868',
    messagingSenderId: '541861431225',
    projectId: 'slrtce9-portal-ba701',
    authDomain: 'slrtce9-portal-ba701.firebaseapp.com',
    storageBucket: 'slrtce9-portal-ba701.firebasestorage.app',
    measurementId: 'G-K74XVC2QYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcpoVRd92feqzRp-z0oE_xtBWz_rE6YDw',
    appId: '1:541861431225:android:e9abd49a749d7829479868',
    messagingSenderId: '541861431225',
    projectId: 'slrtce9-portal-ba701',
    storageBucket: 'slrtce9-portal-ba701.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBE7aljh3Ld0lt28nonzjTfVV1UkZMlwM',
    appId: '1:541861431225:ios:c8fd9b50e2e41bed479868',
    messagingSenderId: '541861431225',
    projectId: 'slrtce9-portal-ba701',
    storageBucket: 'slrtce9-portal-ba701.firebasestorage.app',
    iosBundleId: 'com.example.slrtce9',
  );
}
